apiVersion: v1
kind: Service
metadata:
  name: ${{FD_PROJECT_NAME}}-service
  labels:
    app: ${{FD_PROJECT_NAME}}
spec:    
  type: LoadBalancer
  ports:
  - port: 8500
    targetPort: 9080
    name: http
  selector:
    app: ${{FD_PROJECT_NAME}}-deployment  